echo "The effect of 2 paths, original nobalance dataset, original test dataset...."
python run.py --output_dir=./saved_models_pn1 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_train --train_data_file=../dataset/cdata/nobalance/train_cdata.jsonl --eval_data_file=../dataset/cdata/nobalance/valid_cdata.jsonl --test_data_file=../dataset/cdata/nobalance/test_cdata.jsonl --epoch 8 --block_size 400 --train_batch_size 16 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 2 --d_size 128 --pkl_file=short_2path_cdata.pkl
python run.py --output_dir=./saved_models_pn1 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_eval --do_test --train_data_file=../dataset/cdata/nobalance/train_cdata.jsonl --eval_data_file=../dataset/cdata/nobalance/valid_cdata.jsonl --test_data_file=../dataset/cdata/nobalance/test_cdata.jsonl --epoch 8 --block_size 400 --train_batch_size 16 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 2 --d_size 128 --pkl_file=short_2path_cdata.pkl
python ../evaluator/evaluator.py -a ../dataset/cdata/nobalance/test_cdata.jsonl -p saved_models_pn1/predictions.txt
echo "finish...."

echo "The effect of 4 paths, original nobalance dataset, original test dataset...."
python run.py --output_dir=./saved_models_pn2 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_train --train_data_file=../dataset/cdata/nobalance/train_cdata.jsonl --eval_data_file=../dataset/cdata/nobalance/valid_cdata.jsonl --test_data_file=../dataset/cdata/nobalance/test_cdata.jsonl --epoch 8 --block_size 400 --train_batch_size 16 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 4 --d_size 128 --pkl_file=short_4path_cdata.pkl
python run.py --output_dir=./saved_models_pn2 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_eval --do_test --train_data_file=../dataset/cdata/nobalance/train_cdata.jsonl --eval_data_file=../dataset/cdata/nobalance/valid_cdata.jsonl --test_data_file=../dataset/cdata/nobalance/test_cdata.jsonl --epoch 8 --block_size 400 --train_batch_size 16 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 4 --d_size 128 --pkl_file=short_4path_cdata.pkl
python ../evaluator/evaluator.py -a ../dataset/cdata/nobalance/test_cdata.jsonl -p saved_models_pn2/predictions.txt
echo "finish...."

echo "The effect of 5 paths, original nobalance dataset, original test dataset...."
python run.py --output_dir=./saved_models_pn3 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_train --train_data_file=../dataset/cdata/nobalance/train_cdata.jsonl --eval_data_file=../dataset/cdata/nobalance/valid_cdata.jsonl --test_data_file=../dataset/cdata/nobalance/test_cdata.jsonl --epoch 8 --block_size 400 --train_batch_size 16 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 5 --d_size 128 --pkl_file=short_5path_cdata.pkl
python run.py --output_dir=./saved_models_pn3 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_eval --do_test --train_data_file=../dataset/cdata/nobalance/train_cdata.jsonl --eval_data_file=../dataset/cdata/nobalance/valid_cdata.jsonl --test_data_file=../dataset/cdata/nobalance/test_cdata.jsonl --epoch 8 --block_size 400 --train_batch_size 16 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 5 --d_size 128 --pkl_file=short_5path_cdata.pkl
python ../evaluator/evaluator.py -a ../dataset/cdata/nobalance/test_cdata.jsonl -p saved_models_pn3/predictions.txt
echo "finish...."